version: '3.4'

services:
  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - "18000:8000"
  db:
    image: mysql:5.6
    restart: always
    volumes:
      - ./tests/e2e/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"