FROM github/super-linter:latest

ENV RUN_LOCAL=true
ENV VALIDATE_ALL_CODEBASE=false
ENV VALIDATE_YAML=true
ENV VALIDATE_JSON=true
ENV VALIDATE_MD=true
ENV VALIDATE_BASH=true
ENV VALIDATE_PYTHON=false
ENV VALIDATE_SQL=true
ENV VALIDATE_JAVASCRIPT_ES=false
ENV VALIDATE_JAVASCRIPT_STANDARD=false
ENV VALIDATE_TYPESCRIPT_ES=false
ENV VALIDATE_TYPESCRIPT_STANDARD=false
ENV VALIDATE_DOCKER=true
ENV ACTIONS_RUNNER_DEBUG=false

COPY . /tmp/lint/

ENTRYPOINT ["/action/lib/linter.sh"]