version: '3.4'

services:
  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - "18000:8000"
  db:
    image: mysql:5.6
    restart: always
    volumes:
      - ./tests/e2e/mysql/init.bash:/docker-entrypoint-initdb.d/init.bash
      - ./tests/e2e/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    links:
      - db
      - dynamodb
    environment:
      DB: test
      USER: user
      PASSWORD: pass
      PORT: 3306
    command: >
      poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app