[tasks.install]
description = "Build"
script = ['''
#!/usr/bin/env bash
poetry install
''']

[tasks.lint]
description = "Lint"
script = ['''
#!/usr/bin/env bash
poetry run black ./
''']

[tasks.type_check]
description = "Type Check"
script = ['''
#!/usr/bin/env bash
poetry run mypy --config mypy.ini
''']

[tasks.import_check]
description = "Import Check"
script = ['''
#!/usr/bin/env bash
poetry run isort .
''']

[tasks.pytest]
description = "Test"
script = ['''
#!/usr/bin/env bash
sleep 10
poetry run pytest --verbose -s --cov=src ./tests
''']


[tasks.tests]
dependencies = [
    "lint",
    "type_check",
    "import_check",
    "pytest",
]

[tasks.superlint]
description = "Lint Others"
script = ['''
#!/usr/bin/env bash
docker-compose -f docker-compose.super-linter.yml up
docker-compose -f docker-compose.super-linter.yml down
''']

[tasks.lints]
dependencies = [
    "superlint"
]
